version: "3.8"

services:
  shadowsocks:
    image: dubhad/shadowsocks-rust-v2ray:1.12.0-1.3.1
    restart: always
    volumes:
      - ./certs:/etc/ssl/proxy:ro
    environment:
      - METHOD=chacha20-ietf-poly1305
      - DNS=cloudflare_tls
      - PASSWORD
      - DOMAIN
      - V2RAY_CERT_PATH
      - V2RAY_KEY_PATH
      - V2RAY_PATH
  nginx:
    image: dubhad/nginx-shadowsocks:1.21.0
    restart: always
    volumes:
      - ./certs:/etc/ssl/proxy:ro
    ports:
      - "443:443"
    environment:
      - V2RAY_PORT=8008
      - V2RAY_HOST=shadowsocks
      - DNS_SERVER=127.0.0.11
      - DOMAIN
      - V2RAY_CERT_PATH
      - V2RAY_KEY_PATH
      - V2RAY_PATH
      - REDIRECT_URL
    depends_on:
      - shadowsocks
