version: "3.8"

services:
  shadowsocks_single:
    image: dubhad/shadowsocks-rust-v2ray:1.11.1-1.3.1
    restart: always
    ports:
      - "8443:8008"
    volumes:
      - ./certs:/etc/ssl/proxy:ro
    environment:
      - METHOD=chacha20-ietf-poly1305
      - DNS=cloudflare_tls
      - PASSWORD
      - DOMAIN
      - V2RAY_CERT_PATH
      - V2RAY_KEY_PATH
      - V2RAY_PATH
